### ISSUE TITLE
DOC: Tutorial display setting seems wrong

### ISSUE THREAD

**Issue by endolith** [kdavies4/natu#23]
http://nbviewer.ipython.org/github/kdavies4/natu/blob/master/examples/tutorial.ipynb#Entering-and-displaying-a-quantity says:

> We can change the display unit by setting the quantity's display property:
> In [4]:
> 
> length.display = 'inch'
> length
> 
> Out[4]: 0.0254 m

That doesn't look like inches.  If I do this it works as I would expect:

```
length.display_unit = 'inch'

length
Out[17]: 1 inch
```

but I don't know what the difference is

**Comment by zbeekman** [comment]
Does the jupyter notebook need to be updated? The tutorial still seems to have this problem.
