### ISSUE TITLE
failed: NameError: name 'reduce' is not defined

### ISSUE THREAD

**Issue by MinhHaDuong** [kdavies4/natu#28]
``Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > from natu.units import m
> > > l = 1_m
> > > l
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python3.4/dist-packages/natu/core.py", line 823, in **repr**
> > >     return format(self, 'g')
> > >   File "/usr/local/lib/python3.4/dist-packages/natu/core.py", line 357, in wrapped
> > >     unit = unitspace(_*display_unit)
> > >   File "/usr/local/lib/python3.4/dist-packages/natu/core.py", line 1374, in **call**
> > >     return reduce(lambda x, y: x \* y, factors)
> > > NameError: name 'reduce' is not defined
> > > ``

**Comment by MinhHaDuong** [comment]
Proposed fix:
```
< # Avoid using reduce to be portable between Python v2 and v3
< #            return reduce(lambda x, y: x * y, factors)
<             result = factors[0]
<             for x in factors[1:]:
<                 result = result * x
<             return result
< #
---
>             return reduce(lambda x, y: x * y, factors)
```

**Comment by MinhHaDuong** [comment]
Closing, there is a 
from functools import wraps, reduce
in core.py

**Comment by phuntimes** [comment]
Appears to be an issue again. No `reduce` import in core.py.  Install source is PyPy.

```python
from natu.units import N
print(repr(1.0 * N))
```
```python-traceback
Traceback (most recent call last):
  File "~/.pyenv/versions/scientific/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-9b28d8840f52>", line 1, in <module>
    print(repr(1 * N))
  File "~/.pyenv/versions/scientific/lib/python3.7/site-packages/natu/core.py", line 823, in __repr__
    return format(self, 'g')
  File "~/.pyenv/versions/scientific/lib/python3.7/site-packages/natu/core.py", line 357, in wrapped
    unit = unitspace(**display_unit)
  File "~/.pyenv/versions/scientific/lib/python3.7/site-packages/natu/core.py", line 1374, in __call__
    return reduce(lambda x, y: x * y, factors)
NameError: name 'reduce' is not defined
```
