### ISSUE TITLE
Can you please re-release with commit 261c9cb ?

### ISSUE THREAD

**Issue by nagimov** [kdavies4/natu#29]
https://github.com/kdavies4/natu/commit/261c9cbfaeaaefdc96c39a43fb367983535bd3c8

Without this one doesn't work on Python 3 (`reduce` is not a core python 3 function)

Thanks!

**Comment by KM4YRI** [comment]
So I take it that this project is abandonware now?  If I bother to send a pull request with this change, will the author merge it?

As is, this library is completely unusable on Python 3.

**Comment by pylang** [comment]
What a pity.  Such a great project.

**Comment by kdavies4** [comment]
I'm really sorry everyone. I would like to stay on top of this, but my time and current projects won't allow me to. I would be happy to turn this project over to others if anyone is interested.

**Comment by kdavies4** [comment]
261c9cb is included in v0.1.2
